### ISSUE TITLE
Availability Zone support for OpenStack

### ISSUE THREAD

**Issue by loewa** [elasticluster/elasticluster#642]
We use OpenStack to rollout Elasticluster resources.
A separate availability zone has been setup in order to have the SLURM resources on specialised hardware. We are using special flavors which are only valid on the dedicated machines.

I would like to raise the feature request, 
to have the availability zone to be configured in the config file. This would also give us the possibility to span the SLURM cluster over our 3 datacenter.

Requirement:  Config value for availability zone, when using OpenStack.

Alex

**Comment by riccardomurri** [comment]
I have pushed draft code for this in #644 -- note that I am not able to check the code as we don't run AZs on the local OpenStack infrastructure.

**Comment by riccardomurri** [comment]
(Note I will be on vacation for 2 weeks starting tomorrow, so no further updates on this topic for a while.)

**Comment by loewa** [comment]
Riccardo,

Many thanks for the info. Can I run the code for verification?

Kind regards
Alex

**Comment by riccardomurri** [comment]
Yes, sure -- just check out the code from the branch that the PR refers to.

**Comment by loewa** [comment]
Riccardo,

I am used to use the docker file. Will a find a docker image in the branch?

Kind regards,
Alex

PS: Have a great vacation

**Comment by riccardomurri** [comment]
No, you would need to install from Python sources and switch the source branch.  I'll see if I can build a Docker image with the PR code.

**Comment by riccardomurri** [comment]
You can try to use ElastiCluster docker image tagged `pr644`:

  ./elasticluster.sh --release pr644

**Comment by loewa** [comment]
Riccardo,
Many thanks. I will try it out. Have a nice vacation and thanks for the support!
I hope I can give something back in the future.

Kind regards,
Alex

**Comment by loewa** [comment]
Riccardo,

I have tried it, but it still spins up in the wrong AZ. Is there are possibility to catch the call from the elasticluster to start the VMs at a certain stage. To see that the correct one is requested? Maybe the scheduler is overriding it.

Kind regards,
Alex

**Comment by riccardomurri** [comment]
Hello @loewa 

> s there are possibility to catch the call from the elasticluster to start the VMs at a certain stage. To see that the correct one is requested? Maybe the scheduler is overriding it.

You can maybe attach `tcpdump` to view the HTTP traffic between your ElastiCluster host and the Nova API host?  Or use a web proxy to log/middleman all traffix? (Use the proxy's address as `OS_AUTH_URL`) Or maybe you can ask the OpenStack admins to check the Nova API logs?

Kind regards,
Riccardo

**Comment by loewa** [comment]
Hello Ricardo,

I have one question:
I have tested the change (Availability Zone support for OpenStack (#642)) and it seems to work as expected. Can you implement it in the main version?
How is the search for a logo going forward. Unfortunately I am not a designer or graphics guy.

Kind regards,
Alex

**Comment by riccardomurri** [comment]
Merged into "master", many thanks for testing!
