### ISSUE TITLE
Valid SSH key rejected as invalid

### ISSUE THREAD

**Issue by brisk022** [elasticluster/elasticluster#647]
OpenSSH v8.0 (perhaps earlier?) changed the header of newly generated keys from 'RSA PRIVATE KEY' to 'OPENSSH PRIVATE KEY'. Since paramiko validates private keys by checking their headers, it raises an 'invalid key' exception ([#1313](https://github.com/paramiko/paramiko/issues/1313)). As a result such keys cannot be used with elasticluster.

Paramiko has a [pull request](https://github.com/paramiko/paramiko/pull/1343) to fix the issue. In the meantime, the workaround is to generate another key using an older version of OpenSSH and make sure that the header says 'RSA PRIVATE KEY'.

**Comment by riccardomurri** [comment]
Thanks for taking time to report this and provide a workaround!

I gather there is not much we can do in ElastiCluster, apart from waiting for Paramiko to support the new key format...

**Comment by loveshack** [comment]
Not tested, but you should be able to use a recent openssh with the -m flag to generate, or convert to, a key in the old, insecure format.

**Comment by riccardomurri** [comment]
Paramiko has merged https://github.com/paramiko/paramiko/pull/1343 a few days ago, the fix has been released with Paramiko 2.7.  

I'll update ElastiCluster's dependencies and then close this issue.
