### ISSUE TITLE
Starting 0 instances

### ISSUE THREAD

**Issue by fliem** [elasticluster/elasticluster#672]
I want to create a slurm cluster with different node types (e.g., [here](https://github.com/elasticluster/elasticluster/blob/master/examples/slurm-with-different-node-types.conf)). 

However, on `start` I only want to boot smallworkers and later on if needed `resize` to add largeworkers.
So the config file would have
```
largeworker_nodes=0
```

At the moment this is not possible and will give on `start`
```
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/elasticluster/cluster.py", line 695, in _check_cluster_size
    available = len(self.nodes[kind])
KeyError: 'largeworker'
```

How about changing [L695](https://github.com/elasticluster/elasticluster/blob/dcb9ec3587d5fa4921306fa034bf65dc57cf94af/elasticluster/cluster.py#L695) to 
`available = len(self.nodes.get(kind, 0))`

to allow for this behaviour?

**Comment by riccardomurri** [comment]
Hello @fliem !

Can you try adding 

```largeworker_nodes_min = 0```

to the config?  That setting is meant to support this setup.

**Comment by fliem** [comment]
Thanks @riccardomurri 

I have added this under the `[cluster/slurm]` section.
The same error is thrown.

**Comment by riccardomurri** [comment]
Ok, then it's a bug -- I'll have a look at it tomorrow.

**Comment by fliem** [comment]
Thanks
