### ISSUE TITLE
config for openstack wait for ACTIVE status.

### ISSUE THREAD

**Issue by ianedwardthomas** [elasticluster/elasticluster#676]
Hi,

Our openstack is slow and instances return BUILD status until they become fully ACTIVE.  In openstack provider we _wait_for_status for 30 hardcoded secs.  If we timeout,  then code assumes status was ERROR (if wasn't ACTIVE).  There will be retries,  but as the node in question is deleted for  the error we do the same thing each retry and I end up with no nodes. 

Can we make a config option to override the currently 30 second time for to allow us slow openstack sitautions to adapt, or possibly make the code not count slow BUILD statuses as errors?

Cheers,

**Comment by riccardomurri** [comment]
Done and merged into the "master" branch.

Many thanks for reporting this issue and suggesting the fix!

**Comment by ianedwardthomas** [comment]
It works well.  Thanks!
