### ISSUE TITLE
Trouble authenticating via openstack

### ISSUE THREAD

**Issue by jrieffel** [elasticluster/elasticluster#695]
I can successfully run openstack and nova from the command line, but when I try running elasticluster, I get the following error:

```
keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-477c846b-7530-498d-8df8-8b53dbebaa02)

elasticluster[40929] ERROR Could not start node `worker001`: The request you have made requires authentication. (HTTP 401) (Request-ID: req-566cb8d5-2d78-47ba-97ee-4b5745ecbce5) -- <class 'keystoneauth1.exceptions.http.Unauthorized'>
```

Could you please provide guidance for how to proceed debugging this issue?    Again, I can launch instances with nova from the command line, but not via elasticluster.

**Comment by riccardomurri** [comment]
It looks like authentication with the OpenStack infrastructure was not successful.  Can you please add `-vvvv` to the ElastiCluster command-line and post or send me the complete output?  (WARNING: there could be passwords in there, please take care of removing them.)

Like this; `-vvvv` must be right after the `elasticluster` command:

    elasticluster -vvvv start mycluster

**Comment by riccardomurri** [comment]
The root error seems to be this one:

```
2021-03-10 08:33:39 Johns-MacBook-Pro.local keystoneauth.identity.v3.base[57132] DEBUG Making authentication request to https://kvm.tacc.chameleoncloud.org:5000/v3/auth/tokens
...
2021-03-10 08:33:39 Johns-MacBook-Pro.local urllib3.connectionpool[57132] DEBUG https://kvm.tacc.chameleoncloud.org:5000 "POST /v3/auth/tokens HTTP/1.1" 401 109
2021-03-10 08:33:39 Johns-MacBook-Pro.local keystoneauth.session[57132] DEBUG Request returned failure status: 401
```

Given that the [`/v3/auth/tokens`][1] API call ["uses the password authentication method"][1], my guess would be that you are using the wrong user name (you seem to have `@union.edu@accounts.google.com`, two `@` in your username?), user domain (`OS_USER_DOMAIN`), or password.

Maybe you have credentials in the `~/.elasticluster/config` file that override what is in the environment?  Or you keep the OpenStack credentials in a `clouds.yaml` file, which is not read by ElastiCluster, instead of the environment?

[1]: https://docs.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-unscoped-authorization-detail#password-authentication-with-unscoped-authorization

**Comment by riccardomurri** [comment]
> So my process of elimination it's the OS_USER_DOMAIN_NAME which is not
> specified and therefore left as 'default' in elasticluster.   Is there a
> way to figure out what it *should* be?

Ask the CloudChameleon admins, they will know what domain your account is in.

If you have access to the OpenStack web UI (Horizon), then you should be able to download the "openrc" file (used to be somewhere under "Identity / API access"), which contains the correct value for all the env vars.

**Comment by jrieffel** [comment]
My OpenStackRC file doesn't have those values specified, oddly.

#!/usr/bin/env bash

export OS_AUTH_URL=https://kvm.tacc.chameleoncloud.org:5000/v3

export OS_IDENTITY_API_VERSION=3

export OS_INTERFACE=public

export OS_PROJECT_ID="bee1bbed4d394fb08178758d53bc1e7c"

export ***@***.***@accounts.google.com"

export OS_PROTOCOL="openid"

export OS_AUTH_TYPE="v3oidcpassword"

echo "($OS_USERNAME) Please enter your Chameleon CLI password: "

read -sr OS_PASSWORD_INPUT

export OS_PASSWORD=$OS_PASSWORD_INPUT

export OS_IDENTITY_PROVIDER="chameleon"

export OS_DISCOVERY_ENDPOINT="
https://auth.chameleoncloud.org/auth/realms/chameleon/.well-known/openid-configuration
"

export OS_CLIENT_ID="keystone-kvm-prod"

export OS_ACCESS_TOKEN_TYPE="access_token"

export OS_CLIENT_SECRET="none"

export OS_REGION_NAME="KVM@TACC"

if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi

**Comment by riccardomurri** [comment]
The fact that `OS_IDENTITY_PROVIDER` is set suggests that Chameleon Cloud is using [federated identity][1], which uses a different authentication procedure:

> Unlike other authentication methods in keystone, the user does not issue an HTTP POST request with authentication data in the request body. To start federated authentication a user must access the dedicated URL with IdP’s and protocol’s identifiers stored within a protected URL. The URL has a format of: `/v3/OS-FEDERATION/identity_providers/{idp_id}/protocols/{protocol_id}/auth`.

Can you please ask the admins of Chameleon Cloud if this is the case?

[1]: https://docs.openstack.org/keystone/queens/admin/federated-identity.html

**Comment by jrieffel** [comment]
I can't answer directly - but Federated Identity is one of many
authentication options for logging into the website.  I use my google
credentials (hence the awkward username i imagine).

**Comment by riccardomurri** [comment]
I'm curious -- what was the issue in the end?

**Comment by jrieffel** [comment]
Solving it involved several things:

- originally I think my Chameleon Cloud account was not completely set up
by the admins
- the master branch of elasticluster does not support application
credentials, but a recent branch does, so I used that.
- setting up the proper parameters in the elasticluster config file is not
straightforward to the novice.
- the elasticluster code chokes on confirming fingerprint matches of SSH
keypairs generated to allow EC to talk to the openstack instances and run
ansible etc.   This is caused, I suspect, just by a difference in how EC
and Chameleon confirm key thumbprints.   I ultimately needed to manually
comment-out some lines of the elasticluster python package in order to
circumvent this (not a long term solution).

When I get breathing room in the coming weeks (and while the memory is
still fresh) I may post the process to github, so others may benefit from
it.

The upshot, however, is that I have a 1-master 9-worker SLURM cluster set
up in chameleon, and it is quite exciting!

jr
