### ISSUE TITLE
Outdated project status

### ISSUE THREAD

**Issue by mriedi** [elasticluster/elasticluster#725]
Since 2020 already elasticluster is neither supported nor maintained by the Services and Support for Science IT unit of the University of Zurich.

This should be reflected in the documentation, e.g. the README.rst:

index b556c14f..6c618619 100644
--- a/README.rst
+++ b/README.rst
@@ -26,9 +26,10 @@ on the `elasticluster@googlegroups.com
 <https://groups.google.com/forum/#!forum/elasticluster>`_ mailing-list
 (only subscribers can post).

-The ElastiCluster_ project is an effort of the `Services and Support
+The ElastiCluster_ project originally was an effort of the `Services and Support
 for Science IT`_ (S3IT) unit at the `University of Zurich`_, licensed
-under the `GNU General Public License version 3`_.
+under the `GNU General Public License version 3`_. Since 2020 it is no longer
+maintained nor supported by S3IT or the University of Zurich.

**Comment by riccardomurri** [comment]
Fixed in commit https://github.com/elasticluster/elasticluster/commit/552c51e7a5a0dbd5daad387da871d3a08547f612
